
[testing]
exten = 8,1,Dial(WebSocket/pipecat/c(slin))
exten = 12,1,Dial(WebSocket/pipecat/c(slin12))
exten = 16,1,Dial(WebSocket/pipecat/c(slin16))
exten = 24,1,Dial(WebSocket/pipecat/c(slin24))
exten = 32,1,Dial(WebSocket/pipecat/c(slin32))
exten = 44,1,Dial(WebSocket/pipecat/c(slin44))
exten = 48,1,Dial(WebSocket/pipecat/c(slin48))
exten = 96,1,Dial(WebSocket/pipecat/c(slin96))
exten = 192,1,Dial(WebSocket/pipecat/c(slin192))

