[transport-udp-nat]
type = transport
protocol = udp
bind = 0.0.0.0
external_signaling_address = 127.0.0.1
external_media_address = 127.0.0.1


[testing_account](!)
type = endpoint
context = testing
allow = !all,alaw,ulaw,g722
direct_media = no
trust_id_outbound = yes
device_state_busy_at = 1
dtmf_mode = rfc4733
rtp_symmetric = yes
force_rport = yes
direct_media = no
rewrite_contact = yes

[auth-userpass](!)
type = auth
auth_type = userpass

[aor-single-reg](!)
type = aor
max_contacts = 1
qualify_frequency = 60

[1](testing_account)
auth = 1
aors = 1
callerid = tester <1>

[1](auth-userpass)
password = 1
username = 1

[1](aor-single-reg)
