[pipecat]
type = websocket_client
uri = ws://host.docker.internal:7860/ws
protocols = media
connection_type = per_call_config
connection_timeout = 100
reconnect_interval = 50
reconnect_attempts = 3
tls_enabled = no
